### PR TITLE
Revert "Move turbo/trie and core/types/accounts to erigon-lib (#…

### PR DESCRIPTION
**Pull request by somnathb1**
…#12879)"

This reverts commit bc03aef37692b1d3eb3e8fa481b63efb34a52892.

Has to be reverted due to RLP decoding related issue in ForkchoicUpdate and MiningLoop

### CODE REVIEW

**Review by mriccobene — APPROVED** [review]

**Comment by somnathb1** [comment]
To test
```
kurtosis run --enclave my-testnet github.com/ethpandaops/ethereum-package --args-file .github/workflows/kurtosis/pectra.io
```

**Review by antonis19 — CHANGES_REQUESTED** [review]
Wouldn't it be easier just to fix the RLP issue instead of reverting this?

**Comment by antonis19** [comment]
I need this commit btw, otherwise I'm stuck on my work.

**Comment by somnathb1** [comment]
> I need this commit btw, otherwise I'm stuck on my work.

You can always fork out, fix and raise a PR again. You must confirm, check and possibly fix the issue first.

**Comment by antonis19** [comment]
@somnathb1 but all I did was move the rlp package to`erigon-lib`, there's gotta be an easier to fix it.

**Comment by somnathb1** [comment]
It's not about easy and hard, `main` is potentially broken at the moment. The referenced commit seems to be the culprit for the RLP-related issue. This PR simply points it out. Please confirm if you have identified the issue.
You can always fork out. @antonis19

**Comment by somnathb1** [comment]
Seems like this revert PR does fix the whole kurtosis run - https://github.com/erigontech/erigon/actions/runs/12068690419

**Review by antonis19 — APPROVED** [review]

**Pull request merged**
