### PR TITLE
HD: Removed canonical cache

### PR DESCRIPTION
**Pull request by Giulio2002**

### CODE REVIEW

**Review by mh0lt — COMMENTED** [review]
As its a cache - which is presumably there for performance reasons have you done any testing to check that its removal has no impact ?

**Comment by Giulio2002** [comment]
sure will do a sync, this is mostly a simplification as it is caching a very cheap operation

**Comment by Giulio2002** [comment]
it works

**Review by AskAlexSharov — APPROVED** [review]

**Comment by Giulio2002** [comment]
astryd will make this obsolete so i am closing

**Pull request closed without merging**
