### PR TITLE
monitor attester hit/miss

### PR DESCRIPTION
**Pull request by domiwei**
impl https://github.com/erigontech/erigon/issues/11147
- Use `--caplin.validator-monitor` to enable it.

### CODE REVIEW

**Review by Giulio2002 — CHANGES_REQUESTED** [review]
Can you add the monitoring under a flag, like `--caplin.monitoring`

**Comment by domiwei** [comment]
> Can you add the monitoring under a flag, like `--caplin.monitoring`

Let's name it `caplin.validator-monitor` to distinguish it from system metrics.

**Comment by Giulio2002** [comment]
I ask for a new feauture - can you implement missing blocks counter too?

**Comment by domiwei** [comment]
> I ask for a new feauture - can you implement missing blocks counter too? or do you prefer to do this in an alternate PR

let's do it in another pr, but what is missing block counter?
indicating a proposer should have produced a block but missed it?

**Review by Giulio2002 — APPROVED** [review]

**Pull request merged**
