### PR TITLE
[WIP] Improve RLP encode/decode core types

### PR DESCRIPTION
**Pull request by racytech**
This PR will fix RLP related issues, removing some unused parts and improving some other parts of the code. Benchmarks on Log type encoding/decoding shows that it makes sense to keep using hand-written code.

### CODE REVIEW

**Comment by racytech** [comment]
Move RLP logic in core types to separate file

**Comment by racytech** [comment]
Move some rlp function from ./rlp/encode to ./erigon-lib/rlp/encode

**Comment by AskAlexSharov** [comment]
`Benchmarks on Log type encoding/decoding shows that it makes sense to keep using hand-written code.` - did you compare it with reflection-based code or with rlpgen-based?

**Comment by racytech** [comment]
With reflection-based, on Log struct only

**Comment by racytech** [comment]
let me test it against rlpgen

**Comment by racytech** [comment]
RLPgen:  492243439               48.56 ns/op            0 B/op          0 allocs/op
ByHand: 312318904               79.10 ns/op          144 B/op          4 allocs/op

We should move towards rlpgen, if no objections, didn't know what that is :)

**Comment by racytech** [comment]
Silkworm based approach + reusable buffer: 667179529               35.36 ns/op            0 B/op          0 allocs/op

**Comment by AskAlexSharov** [comment]
> RLPgen: 492243439 48.56 ns/op 0 B/op 0 allocs/op ByHand: 312318904 79.10 ns/op 144 B/op 4 allocs/op
> 
> We should move towards rlpgen, if no objections, didn't know what that is :)

ok for me

**Pull request closed without merging**
