### PR TITLE
Fix caplin RPC attestation rewards being off by one epoch

### PR DESCRIPTION
**Pull request by errge**
Checked against beaconcha.in, against a synced prysm, and against ethereum-beacon-api.publicnode.com.

Catlin is consistently off-by-one (one has to ask for the next numbered epoch to get calculation for the one that one wanted).

@Giulio2002

### CODE REVIEW

**Comment by Giulio2002** [comment]
CI is failed. it requires fixing it

**Comment by errge** [comment]
Yes, I saw, sorry, but I don't have time to learn the unit tests now.

As far as I understand, the tests are wrong, most probably they were created not TDD, but first writing the code and then cementing the result in tests.  I pushed a beaconcha.in api downloader and comparing to that, you can see that caplin is off by one, so the tests must be incorrect.

Hope somebody can help out here with the tests, I'd appreciate.  Cheers!

**Comment by Giulio2002** [comment]
I can fix them for you. i need access to the branch

**Comment by errge** [comment]
@Giulio2002 Thank you so much for the work, I invited you to nilcons-contrib/erigon.

**Comment by errge** [comment]
Tests fixed, sorry for being lazy before, we missed alpha4 because of that :(

Anyways, this is ready to merge now, thanks @Giulio2002 for offering help, but I decided it's time for me to learn how to fix the tests.

**Comment by Giulio2002** [comment]
oh sorry - Erigon had a meetup last week so I had limited time

**Review by Giulio2002 — APPROVED** [review]

**Pull request merged**
