### PR TITLE
get kurtosis assertoor tests to run on each main commit

### PR DESCRIPTION
**Pull request by sudeepdino008**
- `make docker` might increase build time for few minutes, but should be fine (the whole workflow takes 1hr+)

### CODE REVIEW

**Comment by yperbasis** [comment]
> * `make docker` might increase build time for few minutes, but should be fine (the whole workflow takes 1hr+)

We can make this job conditional on "CI-CD build and deploy docker images based on the last commit in the main branch", which updates `erigontech/erigon:main-latest`.

**Comment by sudeepdino008** [comment]
if the "docker build" workflow fails, do we or do we not run kurtosis workflow?
initially I thought to not run it, but now i think still running kurtosis ci (which fails) is good as two errors are surfaced, instead of one (kinda like using 2 alarms spaced 5 minutes apart).

**Comment by yperbasis** [comment]
> if the "docker build" workflow fails, do we or do we not run kurtosis workflow? initially I thought to not run it, but now i think still running kurtosis ci (which fails) is good as two errors are surfaced, instead of one (kinda like using 2 alarms spaced 5 minutes apart).

The docker build job is a basic one to build erigon with ancillary binaries and to publish the image on docker hub. If fail to build erigon, there's little point in running assertoor tests :)

**Comment by sudeepdino008** [comment]
> > if the "docker build" workflow fails, do we or do we not run kurtosis workflow? initially I thought to not run it, but now i think still running kurtosis ci (which fails) is good as two errors are surfaced, instead of one (kinda like using 2 alarms spaced 5 minutes apart).
> 
> The docker build job is a basic one to build erigon with ancillary binaries and to publish the image on docker hub. If fail to build erigon, there's little point in running assertoor tests :)

copy.

Can we merge this to main. It'll trigger the docker build and we can see if that triggers this workflow.

**Pull request merged**
