### PR TITLE
drop own bloom fork

### PR DESCRIPTION
**Pull request by AskAlexSharov**

### CODE REVIEW

**Comment by antonis19** [comment]
Waiting for this tests to complete before merging: https://github.com/erigontech/erigon/actions/runs/12115936119

**Review by antonis19 — APPROVED** [review]

**Comment by AskAlexSharov** [comment]
this one is also red: https://github.com/erigontech/erigon/actions/runs/12115582397/job/33774223604?pr=12886

**Comment by antonis19** [comment]
@AskAlexSharov rerunning that test

**Comment by AskAlexSharov** [comment]
closing in favor of: https://github.com/erigontech/erigon/pull/12967

**Pull request closed without merging**
