### PR TITLE
Strongerrunner

### PR DESCRIPTION
**Pull request by dvovk**
@AskAlexSharov No I haven't known it, thanks.

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
@dvovk do you know about `-p 2` in https://github.com/erigontech/erigon/blob/main/Makefile#L68 ?

**Comment by dvovk** [comment]
For some reasons new runner doesn't work at this branch so the last place to check is the main branch. After runners speed comparison I am going to remove slowest one.

**Review by lystopad — APPROVED** [review]
From devops perspective workflow configuration looks ok.

**Comment by AskAlexSharov** [comment]
`Integration tests / tests (ubuntu-22.04) (pull_request) Successful in 34m ` - in main i saw `29m`

**Pull request merged**
