### PR TITLE
diagnostics: added func to grab heap profile (#11643)

### PR DESCRIPTION
**Pull request by dvovk**
- Added functionality to grab the heap profile by calling the diagnostics endpoint
- Added support to pass heap profile file to diagnostics UI through WebSocket

### CODE REVIEW

**Comment by awskii** [comment]
hmm, we can get heap profile from pprof endpoint locally, why need another?

**Comment by dvovk** [comment]
@awskii  This was added in purpose that diagnostics UI will show profile data (started with heap). It is possible to connect to running node without `--pprof` and query heap profile. Also I am going to add some history where you can compare with previous data.
Here is example:

https://github.com/user-attachments/assets/22b3e7af-94c5-4595-846f-3a605be7654a

**Comment by awskii** [comment]
wow thats nice.

**Review by awskii — APPROVED** [review]

**Comment by dvovk** [comment]
> wow thats nice, but still why cant fetch them from localhost where diagnostics daemon is running?

I didn't understand what you mean under "diagnostics daemon is running" 
in order to get heap or other profile you need to setup `--pprof` flag and visit `127.0..../debug/pprof` endpoint. As diagnostics is running by default I need an endpoint to query this data without `--pprof` flag. So it will allow to read profile data without restart a node.

**Pull request merged**
