### PR TITLE
Caplin: simplified cache-query

### PR DESCRIPTION
**Pull request by Giulio2002**
This PR should simplify the cache system during reorgs by removing caches which should not be bottlenecks anymore

### CODE REVIEW

**Comment by Giulio2002** [comment]
close #13204

**Comment by Giulio2002** [comment]
close #13217

**Comment by Giulio2002** [comment]
misplaced a lock. now it will also close #13229

**Comment by errge** [comment]
hey @Giulio2002

Thank you for working on this, I'd be happy to test drive this.

Can you please ping me when/if you can guarantee the following about the PR:
  - no change of the on-disk format (so if something goes wrong, I can just rollback to official alpha7 without resync)
  - PR is ready for testing.

If we can meet these conditions, I can put this on my machine and test it with the same workflow that causes the crashes now.

**Comment by Giulio2002** [comment]
no change in disk format. ready for testing. the only thing it can happen is that the you get an invalid state root somewhere down the line.

**Comment by errge** [comment]
> no change in disk format. ready for testing. the only thing it can happen is that the you get an invalid state root somewhere down the line.

Sorry, I'm not familiar with the internals enough to parse.  If this happens, that causes a crash and I'm fine?  Or will I have to somehow rollback my disk state to be able to rollback to alpha7?  So would this state root be saved somewhere inhibiting recovery in case of failure?

**Comment by Giulio2002** [comment]
if that happens, you can just restart

**Comment by errge** [comment]
Thank you, much appreciated your friendly handling of the issue, I will do the build and report back after a day or two

**Comment by errge** [comment]
The fix works, crash was happening every 1-2 hours under my usage, now didn't crash for 6 straight hours.

Thank you!

**Pull request merged**
