### PR TITLE
add slot data from electra

### PR DESCRIPTION
**Pull request by shotasilagadze**
Adding slot data to support to Antiquary

### CODE REVIEW

**Review by domiwei — APPROVED** [review]
lgtm

**Comment by Giulio2002** [comment]
Hey, you need to add electra `antiquary_test`. you need to get yourself a state from consensus-spec-test `random` tests

**Comment by Giulio2002** [comment]
> > Hey, you need to add electra in `antiquary_test.go`. you need to get yourself a state from consensus-spec-test `random` tests
> 
> Ok, but to confirm, that test would be testing state transition in electra using antiquary right? It's not exactly `slot data` related test.

no it is very much related as I will not be merging something that might break stuff. test it in antiquary

**Comment by Giulio2002** [comment]
also it is also mentioned in the issue that the test must exist

**Review by Giulio2002 — CHANGES_REQUESTED** [review]
revoke approval

**Comment by Giulio2002** [comment]
hey - i saw you requested a review again. if those tests are not in, this wont be merged

**Review by Giulio2002 — APPROVED** [review]

**Pull request merged**
